### ISSUE TITLE
Preview(s) of Coq between official releases?

### ISSUE THREAD

**Issue by jfehrle** [coq/platform#107]
For discussion of @MSoegtropIMC's comment in [#14354](https://github.com/coq/coq/pull/14354#issuecomment-857497716)

> Maybe I should do a monthly best pick preview Coq Platform. For me it is quite hard to test all the debugger enhancements from @jfehrle in my daily work, because I need so much stuff to compile, which usually doesn't compile right at the spot I want to test it.

**Comment by Zimmi48** [comment]
>We could also consider creating preview branches for code changes for which we'd like more user feedback. They could omit any incompatible code changes that go into master meant for the next release.

For some features, that might be doable, especially if they are merged early into the release cycle, while for some others it might be more difficult to extract them without the earlier backward-incompatible changes. That being said, it might be worthwhile to do both (monthly snapshots and feature previews).

**Comment by MSoegtropIMC** [comment]
But all in all this must be something living in the extra-dev branch of the Coq opam repo, so that it is easily installable. I rather imaging that one creates preview version packages and sets these to s specific commit and updates these opam packages as needed. Even tracking a dedicated feature branch is likely not appropriate, because this also might sometimes work and sometimes not - unless one considers to have release branches of feature branches ...

**Comment by Zimmi48** [comment]
How would you write the version numbers for all these packages?

**Comment by MSoegtropIMC** [comment]
This needs to be discussed, but I would say that these packages should be deleted after a release, so that it shouldn't get too bad.

**Comment by Zimmi48** [comment]
OK, if eventual deletion is in order, then an idea would be to use a `.dev` version scheme which points to a commit that is manually updated instead of pointing to a branch. That way, we guarantee that the package set is compatible together at any point, however, we do allow for updates.

**Comment by jfehrle** [comment]
Would we be able to include Coq PRs, potentially with overlays, that are not yet committed in master?  If each user compiles the platform through opam, is there a way to do something akin to overlays?

If you're creating a monthly preview of master, there could be transient failures for some packages and perhaps accumulated incompatible changes (mostly mitigated by prior deprecations).

For a feature branch, taking the debugger as an example: each of its 2 open PRs have overlays:
#14252 has an overlay for coqtail, which could be ignored since coqtail doesn't support the debugger.  #14354 adds a field to Loc.t that requires an overlay only for elpi.  (If @ejgallego figures out how to attach the same info to the Ltac object then it may not need an overlay.)

> For some features, [preview branches for code changes for which we'd like more user feedback] might be doable, especially if they are merged early into the release cycle, while for some others it might be more difficult to extract them without the earlier backward-incompatible changes.

My thought was to create a new branch based on 8.14 and merge only the needed PRs into it in order to maxime stability.  Creating such a branch should be workable for many but not every new feature.

**Comment by MSoegtropIMC** [comment]
@jfehrle : one can point an opam package to any commit - potentially even on a fork. So e.g. in case of a debugger preview, it could be a commit or even a tag of a branch on your fork.

@Zimmi48 : regarding naming: I guess it could be `~feat-xyz` for a preview of feature xyz and `~prev-mm` for a preview of month `mm`.

**Comment by jfehrle** [comment]
> potentially even on a fork. So e.g. in case of a debugger preview, it could be a commit or even a tag of a branch on your fork.

It could point to a jfehrle fork of elpi, for example?  That would make it pretty simple for the debugger example.

For monthly releases from master, you might be forced to use the latest version of the package (incorporating merged overlays since the last Coq release), which may be less stable.

**Comment by MSoegtropIMC** [comment]
> It could point to a jfehrle fork of elpi, for example? That would make it pretty simple for the debugger example.

Not sure what elpi has to do with it, but I don't see a good reason for not providing feature preview opam packages in extra-dev, which point to forks, as long as it is ensured that nobody gets such a package without explicitly asking for it, which is mostly a question of package version naming.

I think one has to ensure that all feature preview packages have a version which is "older" than "dev". Unfortunately I don't see a way to avoid that opam would upgrade from one feature to another because the name of the other feature is "newer" in terms of version ordering, but I think this is OK, if one knows it.

**Comment by jfehrle** [comment]
I assumed you were familiar with the overlay mechanism used in CI, which is described [here](https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md).

coq/coq/pull/14354 has this breaking change to `loc.mli`:

![image](https://user-images.githubusercontent.com/1253341/121818286-0db47880-cc3b-11eb-9a4f-c9ab5044e107.png)

so elpi won't compile with coq/coq/pull/14354 in Coq without the overlay PR LPCIC/coq-elpi/pull/248.

You think there's a way to include the elpi patch in opam without affecting users who want to stay on the official release?  The [switch mechanism](https://opam.ocaml.org/doc/Manual.html#Switches) and the "pinning" mechanism look promising, maybe that's what you had in mind?

**Comment by MSoegtropIMC** [comment]
@jfehrle : I know the overlay mechanism, but I was not aware that the debugger has changes affecting elpi.

One could e.g. create in the opam extra-dev repo a patched elpi opam package (say elpi.overlay-pr14345) and state in the opam file that this version is compatible with your specific version of coq, but no other. Since elpi.overlay is "newer" than elpi.dev according to opam's version comparison rules, it would pick this elpi version for your coq. For other coq.dev versions it would still pick elpi.dev, since the elpi.overlay package explicitly says that it is only compatible with your branch of coq.

So the trick would be to have an "overlay version space" which is always newer than the "dev version space" and overlay versions always require a specific patch version of coq.

The downside is that if someone already has elpi.dev installed, it would keep it. One can either live with this - I guess people trying this anyway would always create a fresh opam switch - or find a way to state that your version of coq is incompatible with the normal dev version of elpi without requiring it (not sure if this is possible).

Another option would be that you simply require this version of elpi in your version of Coq. The downside of this would be that elpi would always be installed, but one could be sure that it is the correct version.

So yes, there are ways of doing this, and indeed I think supplying such packages would bring us forward. If you want, I can create such packages as a test (independent of Coq platform).

**Comment by jfehrle** [comment]
If we're not sure of the behavior, then testing is a good idea.  Unless you're especially eager, I think we could wait 3-4 weeks before trying to create a debugger preview, which will give me time to add some additional essential features to the debugger (e.g. display of the stack and variable values).

**Comment by MSoegtropIMC** [comment]
I am sure of the behavior, but I am not sure what behavior users would appreciate most. Of cause this also needs testing. 3-4 weeks fits my timeline well.

**Comment by MSoegtropIMC** [comment]
I think with the multi-version support it is sufficiently easy to create preview releases by supplying an additional pick. I also plan to have besides the dev pick a "coqci" pick which mimics coqci and should be more stable than dev, but in a later release.
