### ISSUE TITLE
Add deriving to the Coq Platform package

### ISSUE THREAD

**Issue by anton-trunov** [coq/platform#114]
[deriving](https://github.com/arthuraa/deriving) is very useful and is a part of the Mathcomp universe.

**Comment by arthuraa** [comment]
Hi everyone,

I am happy to hear that people are interested in including deriving in the platform! I confirm that my intention is to continue maintaining and developing the package for the foreseeable future, and to eventually make a more stable release. However, I would still like to wait a bit before taking it out of the beta stage, since I would like to get more feedback from users.

Thanks,
Arthur

**Comment by MSoegtropIMC** [comment]
@arthuraa : thanks for letting us know. So is the conclusion that I include it in the "extended" set?

**Comment by arthuraa** [comment]
@MSoegtropIMC Yes, "extended" is fine for now for me.

**Comment by MSoegtropIMC** [comment]
Perfect, thanks!
