### ISSUE TITLE
Coq Platform branch used in Coq's CI is broken

### ISSUE THREAD

**Issue by ejgallego** [coq/platform#125]
The Coq Platform branch `dev-ci` used in Coq's CI has been broken for a dozen of days at least.

I have tried a fixup [here](https://github.com/coq/coq/pull/12425) , however the problem seems deeper.

This is a serious regression, as it means people is merging Coq PRs with the windows check in red all the time.

**Comment by MSoegtropIMC** [comment]
@ejgallego : just wanted to ask what the status of this is. From my point of view it does work - except that coq-interval dev doesn't build. But Coq + CoqIDE plus all other packages do build. See (https://github.com/coq/platform/runs/3472574427?check_suite_focus=true#step:4:1669).

**Comment by ejgallego** [comment]
It does work indeed, thanks.

I am refining the way this is used from Coq CI [here](https://github.com/coq/coq/pull/12425), and in particular removing some tricky code that is not needed in the github runners.

Feel free to close and move the discussion to Coq's PR, I will ping when it is ready for review.

**Comment by MSoegtropIMC** [comment]
Fine. Please note that soon there will be a new master branch which includes support for dev builds. This should be better maintained than the current dev-ci branch because all the OS dependent infrastructure (which is what broke here) is shared with  the other versions. I will ping you, when it is ready. The usage should be identical except for an additional command line option to pick the version (dev).
