### ISSUE TITLE
[feature request] Phase splitting

### ISSUE THREAD

**Issue by ejgallego** [coq/platform#131]
Some platform users could benefit from being able to call the script in a more fine-grained way, in particular:
- it would be nice to split the cygwin setup, from the rest of the build
- it would be nice to split installing the opam deps from actual coq packages [using `opam install --deps-only`]

This is feedback from https://github.com/coq/coq/pull/12425

**Comment by Zimmi48** [comment]
>it would be nice to split installing the opam deps from actual coq packages [using opam install --deps-only]

Would be also useful for use cases such as https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/CoqIDE.20.22coqtop.20died.20badly.22.20with.20Coq.208.2E14.20dev/near/252419910.

**Comment by MSoegtropIMC** [comment]
Splitting the cygwin setup from running the script is already supported (since pretty much ever). The option to the setup batch file is `-build=N`. With this the Windows script ends after setting up cygwin - just at the point where it would execute the bash script.

Regarding the second point: I can add an option to run the main install with `--deps-only` or `--depext-only`. Probably it would be best to just allow to give an arbitrary extra command to the opam install. The depext stuff might need some extra handling though since the scripts have a mechanism to run most depext stuff early (to avoid having to give the sudo password multiple times).

**Comment by ejgallego** [comment]
Sounds good @MSoegtropIMC ; and would help quite a bit for CI.

I guess the tweaks are easy, but IMHO we should have a CI job here that does the "split" setup, to ensure it keeps working.

**Comment by MSoegtropIMC** [comment]
@ejgallego : I just review this and think that meanwhile this is all there. Coq Platform has the following options:

- `-opamonly` : this stops after installing opam, depext packages and dev package patching and before the main `opam install`
- Windows has in addition the `-build=n` option to stop after cygwin setup

In addition there is this option used by the Coq CI:
 
- `-override-dev-pkg=name=url` : this allows to create a local copy of a dev package with patched source URL - several such options can be given.

So I will close this issue.
