### ISSUE TITLE
Coq installer makes binaries available?

### ISSUE THREAD

**Issue by mgree** [coq/platform#149]
#### Description of the problem

We teach using Coq at an introductory level (second course for CS majors), where many of the students aren't particularly familiar with the terminal. The startup cost---whether we use CoqIDE or Proof General---is fairly high; in both setups, we've had to use `coqc` on the terminal to manually compile things.

It would be helpful to us if CoqIDE, on installation, either:

(a) symlinked `/usr/local/bin/coq*` to the installation location (e.g., /Applications/CoqIDE\ 8.10.2.app/Contents, or
(b) added the installation location to the user's PATH

The precise way to do this (and possibly, best course of action) may be platform dependent.

#### Coq Version

8.10.2 on macOS and Windows.

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : On Mac it is tricky, because the contents of an application package is not (usually) visible, so one can't put anything in there a non expert user can be expected to find. What one could do is to include a shell script at the top level of the .dmg file one can move e.g. to the desktop.

But in general I would say there is no bullet proof way to supply a working shell environment for people who don't know what a shell is.

It might be easiest to explain what path command you have to issue on macOS or Windows.
