### ISSUE TITLE
macOS: give installers Coq version specific names

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#164]
The macOS DMG installers produced by CI have all the same DMG and app name - the name should depend on the Coq version.

**Comment by tech189** [comment]
It would also be good if the Windows installers had a stable naming pattern so that package managers could run a regex on the releases page to get the latest installer!

E.g. the current release title is `2022.01.0` but the installer file name contains `2022.01` without the trailing `.0`, while older versions had different patters of no Coq version or no release version. Maybe the installer file name should leave out the Coq version altogether?

**Comment by tech189** [comment]
Thanks for improving the macOS releases, should I make separate issue for the Windows releases?

**Comment by MSoegtropIMC** [comment]
It wouldn't hurt, but it is not required either - it will be done anyway

**Comment by MSoegtropIMC** [comment]
Ah I didn't know that there is a Scoop package for Coq Platform - maybe we should put this in the docs.

**Comment by tech189** [comment]
Sure, would you like me to make a PR adding a repology badge for Scoop's package to the README or something else?

**Comment by MSoegtropIMC** [comment]
Yes, but please in the Windows specific Readme. Please mention it in the few lines of introduction which list the available install methods and either create a new section "package managers" and put it there are just put the Scoop link / badge as a bullet in the install methods section.

Btw.: how does scoop does it? Download and run the installer interactively?

**Comment by tech189** [comment]
Will do!

It downloads the installer and extracts it as a zip file! Then it removes installer related files and creates shims for `coqtop.exe, coqc.exe, coqchk.exe, coqidetop.opt.exe` so that they are in the PATH and can be run from anywhere. Finally it sets the environment variable `COQBIN` to the `bin` folder and creates a start menu shortcut for CoqIDE.

**Comment by MSoegtropIMC** [comment]
I see. In the future we will likely ave a more modular and .msi based design.

Btw.: I now aligned the MacOS and Windows names, e.g.:
```
Coq-Platform-release-2022.03.0-version~8.15~2022.03.dmg
Coq-Platform-release-2022.03.0-version~8.15~2022.03-arch-x86_64.exe
```
One can think about replacing the `arch-x86_64` with ẁindows-x84_64` and insert an `-macos` at the end for the Mac installer. What do you think?

**Comment by MSoegtropIMC** [comment]
Btw.: I don't think you should be downloading ZIP files. In the releases the files are offered unzipped (the effect of ZIP compression is marginal for installers).

Scoop should download from the links given in https://github.com/coq/platform/releases.

**Comment by tech189** [comment]
> One can think about replacing the arch-x86_64 with ẁindows-x84_64and insert an-macos` at the end for the Mac installer. What do you think?

Yes that would be clearer! Thanks for changing it.

> Btw.: I don't think you should be downloading ZIP files.

Scoop downloads the exe https://github.com/coq/platform/releases/download/2022.01.0/Coq-Platform-8.14.2022.01-installer-windows-x86_64_signed.exe (or the `i686` version on 32bit systems) and then unpacks it rather than running it. Scoop does this to make sure all files of an app are in one folder rather than scattered across the computer (some installers write to Program Files, AppData, ProgramData, or their own folder under `C:\`) - so Scoop will unpack all files inside the Coq Platform installer to `~\scoop\apps\coq\2022.01.0\` for the current version.

**Comment by MSoegtropIMC** [comment]
I see - makes sense. Btw.: I plan to switch to MSI installers some time.

**Comment by Zimmi48** [comment]
I agree that the installer names should contain the name of the OS because not all users will be able to tell the difference based only on the file extension.
