### ISSUE TITLE
Platform for 8.15.0

### ISSUE THREAD

**Issue by SkySkimmer** [coq/platform#191]
8.15.0 has been tagged. Please do the "This is now delegated to the platform maintainers" section at https://github.com/coq/coq/issues/15014

**Comment by MSoegtropIMC** [comment]
Thanks for the note!

I guess you are the release manager for 8.15?

**Comment by SkySkimmer** [comment]
yes

**Comment by MSoegtropIMC** [comment]
OK. I am still fairly busy but will start the picking process the weekend - the generation of the picking issues is fairly automated.

**Comment by Zimmi48** [comment]
Given that the 2021.11 release has been delayed significantly, I think it would make sense to first:
- rename this release into 2021.01 (especially as the track creation request on Snap has not been filled yet AFAIU)
- include both 8.14.1 has the default package pick and 8.15.0 with a beta package pick.

However, I recommend avoiding anything that is likely to delay the platform release further, i.e., not trying to have a perfect beta pick or even a complete one, and not attempting to include anything new that is not absolutely necessary and is not yet ready (IIUC this was the main reason for the delay).

If you need help with some of this, I don't have a lot of time, but I can try to give you some.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : yes, sorry for that - I was just really super busy at work and privately in December and then really needed a bit of a break.

The main thing open are the ATPs for CoqHammer - just when things consolidated there was a major rework of the opam Z3 package which I need to follow up on. The plan is btw. to release Coq Hammer in "full" but only for Mac and Linux. There is currently no way to run it on Windows (it makes heavy use of forks). But I think this is not that bad because the tactics run fine on Windows, so one would need Mac/Linux only to create the hammer proofs, but not to run through proof scripts which use hammer scripts. I think this is acceptable (for the time being).

My plan is to proceed as follows:

- do a first pick for 8.15, so that we see what works and what not. I started with this already, but not yet finished. This could then be published as a 8.15 Coq Platform beta. This is a pre requisite for sending out the pick requests to all package maintainers, because the requests contain information if the latest tag compiled with 8.15 and/or if patches are required.

- finalize the current release - I am currently looking at the status.

**Comment by MSoegtropIMC** [comment]
P.S.: do you have preferences on for which packages I should do patched opam packages (say using an untagged commit on master) so that this could be called a beta?

See the "requires 8.14" comments in [pick 8.15](https://github.com/MSoegtropIMC/platform/blob/updates-2022-01/package_picks/package-pick-8.15%7E2022.01.sh)

**Comment by Zimmi48** [comment]
>What "should" and "must" dates should I put into the request? Usually I use 6 weeks for "should" and 3 months for "must". Is this agreeable?

This is fine, but more importantly than these two dates, I think you should also include a note that if they prepare a new version in less than a week, then it can be included in the beta pick (sometimes compatible versions are already available, all that remains to do is to put a tag and release on opam, and people are available to do it quickly).

>Btw.: IMHO 8.15 vx 8.14 breaks a bit more than 8.14 vs 8.13. Is this expected? I have seen quite a variety of errors.

The most breaking change was that `apply with` doesn't rename its arguments and this triggered quite a number of overlays indeed: https://github.com/coq/coq/pull/13837

So I expect a lot of errors are related to this change.

**Comment by Zimmi48** [comment]
>P.S.: do you have preferences on for which packages I should do patched opam packages (say using an untagged commit on master) so that this could be called a beta?

Yes, if that's not too much work, let's have a patched package for the ones that are in Coq's CI (and thus have a commit that is compatible with Coq 8.15) if they do not get tags in time for the beta pick: this means Math-Classes and CoRN (but I can actually tag these), HoTT, Equations, UniCoq, Mtac2, Iris, CompCert, VST, and coq-dpdgraph.

**Comment by Zimmi48** [comment]
For these, you do not even need to investigate to find a suitable commit, you can just use the information from https://github.com/coq/coq/blob/v8.15/dev/ci/ci-basic-overlay.sh.

**Comment by MSoegtropIMC** [comment]
But I guess the idea is to make a "preview release" now, ask the people to tag instead of using patch opam packages on untagged commits. I would find 2 weeks a more reasonable time line for this.

**Comment by Zimmi48** [comment]
My point is that:
1. we should not keep delaying the next platform release (which is the first which will provide Coq 8.14 in non-beta)
2. a beta pick doesn't have to be as clean as a non-beta pick
3. many people react very quickly when asked to do something anyway

**Comment by MSoegtropIMC** [comment]
I see. So the plan is:

- create the "please pick" issues, noting that everything in within 1 week will be in the beta.
- fix the remaining issues (= CoqHammer)
- release in one week.

**Comment by MSoegtropIMC** [comment]
I just creates all the "please pick / tag" issues.

The tracker meta issue is #193.

**Comment by MSoegtropIMC** [comment]
I will close this issue now - it is replaced by #193.
