### ISSUE TITLE
Windows: update license text for VST

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#249]
The license text shown for VST is outdated - likely one doesn't need to show a license text at all any more, but this must be double checked.

One should take this as opportunity to generally review the display of licenses during the Windows installation.

**Comment by andrew-appel** [comment]
Correct.  

The Coq Platform 2022.04 release contains an obsolete VST license.

The license displayed in the "Coq Setup" in my Windows installer for [this release](https://github.com/coq/platform/releases/download/2022.04.0/Coq-Platform-release-2022.04.0-version_8.15_2022.04-windows-i686_signed.exe),

displays like this one:
https://github.com/PrincetonUniversity/VST/blob/v2.9/LICENSE

but the current LICENSE for VST 2.9.1 (which is the tag
supplied for the Coq Platform 2022.04 for Coq 8.15) is,

https://github.com/PrincetonUniversity/VST/blob/v2.9.1/LICENSE

Furthermore, because this license is now fully open-source
(it is a standard BSD 2-clause license), there is no longer
any need to display the VST license to the user in a dialog box.

Please fix this before the next Coq Platform release.

**Comment by MSoegtropIMC** [comment]
@andrew-appel : since the same installer script is used for all versions of Coq Platform, I need to detect this. I have two issues with this:

1.) In the VST opam packages, the license points to (https://raw.githubusercontent.com/PrincetonUniversity/VST/master/LICENSE) - it should be the specific tag - I guess I messed this up originally.

2.) It would be easy to detect if I can leave away the license question alltogether if the opam license would be an SPDX compatible entry. I think for the opam package it is fine to just say BSD even if not all of VST is BSD, as long as what the opam package installs is BSD. I don't think one needs to link the file in the VST repo.

I would suggest the following: I look at `opam show coq-vst -f license:` and if it is SPDX, I don't ask, otherwise I expect it is an URL which I then download and use as display text.

Can you please take care that the opam packages are fixed accordingly? I am fairly busy with the release. I leave it as is for the beta but want to fix it for the release (in 2 weeks or so).
