### ISSUE TITLE
Add MathComp Multinomials to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#25]
MathComp Multinomials is a library for monoidal rings and multinomials. 

Multinomials is used in another key project, [CoqEAL](https://github.com/CoqEAL/CoqEAL), which allows data refinement of Coq code. In its role as dependency of CoqEAL (and other projects such as [grobner](https://github.com/thery/grobner)) I propose that it is included in the Coq Platform.

As far as I can tell, the maintainers of Multinomials are @strub and @cohencyril.

**Comment by strub** [comment]
Hi. I am going to release a major version of the library in the next 1 or 2 months. I would prefer to have the latter included in Coq Platform.

**Comment by proux01** [comment]
@strub note that the current version is used in CoqEAL, so we may still need it?

**Comment by MSoegtropIMC** [comment]
Indeed in Coq Platform I can only have one version, so you need to agree which this is.

**Comment by proux01** [comment]
Could you please recall us the deadlines?

**Comment by MSoegtropIMC** [comment]
For 8.14 the Coq Platform release should happen about 4 weeks after the Coq release. It should be later only in exceptional cases. Having added so many packages might count as such a case. So for for 8.14 I would like to ship the release some time in November - preferably early November.

The extended pick of 8.13 I will publish fairly soon (days). For this I will use the latest published release.

**Comment by proux01** [comment]
Thanks, so this doesn't sound very compatible with "1 or 2 months". Shouldn't we stick to the current version for 8.14 and get the next major versions in 8.15 (likely in a few months) so as to not delay further the introduction of CoqEAL?

**Comment by strub** [comment]
> Thanks, so this doesn't sound very compatible with "1 or 2 months". Shouldn't we stick to the current version for 8.14 and get the next major versions in 8.15 (likely in a few months) so as to not delay further the introduction of CoqEAL?

Yes, let's stick to the current version for 8.14.

**Comment by proux01** [comment]
Thanks!

**Comment by MSoegtropIMC** [comment]
Thanks for the confirmation!

One feature I recently added to Coq Platform is to support several "picks". This was mostly intended to have up to date OS and installation support also for older versions of Coq, so that it is easier to port older projects to recent Coq, but it also has the advantage that once can publish additional updated picks as minor release in shorter intervals. E.g. the currently "in production" Coq Platform 2021.09 does support the original pick for 8.13 from February, but also an updated and substantially extended pick.

**Comment by Zimmi48** [comment]
> but it also has the advantage that once can publish additional updated picks as minor release in shorter intervals

Hum. We never discussed doing new picks in minor releases. Are you sure this is in line with our previous discussions and conclusions on the platform versioning scheme?

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : the idea is to keep the existing picks and also the default pick, but just add a new independent pick. I think this does make sense because 6 months between major releases is a long time. But let's not argue about this now. We will see what the future brings and what makes sense.

@strub : since the coqeal package depends on it, I would like to include this package in the "full" level, but I am still missing some sort of statement that you plan to maintain it for the foreseeable future.

**Comment by MSoegtropIMC** [comment]
As discussed, I will include this package in the "extended" level, but would prefer to include it in the "full" level in the next release (likely November). This also affects CoqEAL.

**Comment by strub** [comment]
Fine with me.

**Comment by MSoegtropIMC** [comment]
The maintainer agreement can be found here:

> What I can say is that:
> 
> * although I did not initiate the inclusion in the Coq Platform, I am happy with it,
> * the project is still active & maintained (this includes having its last version compatible with the last version of Coq & MathComp).

so I will move MathComp Multinomials and CoqEAL to the "full" level.

**Comment by MSoegtropIMC** [comment]
Move from 'extended' to 'full' done in PR (https://github.com/coq/platform/pull/146).

So we are all set and I will close this issue.
