### ISSUE TITLE
How do I download the "full" platform version of Coq?

### ISSUE THREAD

**Issue by enjoysmath** [coq/platform#279]
I see no option for that, just a list of packages on the page describing the base, ide, and full levels.

**Comment by Zimmi48** [comment]
The full version is currently what you get when using any binary installer. If you use the interactive scripts instead, it will ask you which version you want to install.

**Comment by enjoysmath** [comment]
Thank you, for the response (and quick!).  You can close this now.

I have downloaded and installed.  It works!    Amazing software.   Opposite
of crapware.

I love Coq!

Coq > Lean4, most definitely.

**Comment by MSoegtropIMC** [comment]
One could consider to group the packages by level to make this clear - the package selection view should support hierarchical structures (trees).

The mean reason I didn't do this up to now is that CompCert must be explicitly selected (that's what I agreed on with Xavier). Selecting it by selecting the "full" level would not be OK.

One option would be to have a separate category "full level - non open source". The VST library meanwhile changed - it installs only GPL parts of CompCert.

@enjoysmath : thangs for bringing this up - essentially the reason why things are as they are is that the installer is much older than the Coq Platform levels.

**Comment by Zimmi48** [comment]
> The main reason I didn't do this up to now is that CompCert must be explicitly selected (that's what I agreed on with Xavier). Selecting it by selecting the "full" level would not be OK.

But this is the behavior only on Windows. He is fine with CompCert being silently included in macOS / Snap?

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I had a private email discussion with @xavierleroy last year on the inclusion of CompCert in the macOS Installer and we concluded that it would be sufficient to include the ReadMe file at the top level of the DMG with an explicit note on the non free nature of CompCert in a prominent place. Indeed there was no explicit discussion on the inclusion in Snap, but the ReadMe file of the snap is similar and also has a note on the CompCert license in the header (see: https://github.com/coq/platform/blob/main/doc/README%7E8.15%7E2022.04.md).

@xavierleroy : I think it would be best to create an issue in Coq Platform were you summarize and document the conditions for including CompCert, so that others can find them in case. For your reference, the email discussion we had on this topic was March 14th/15th 2021.

In some not so far future I want to have a binary package system for all platforms (Coq is growing faster than average DSL speeds ...) which would allow a similar handling as in Windows.

**Comment by MSoegtropIMC** [comment]
I would summarize the discussions I had with Xavier so far that we should do as much as possible to make the user aware of the license situation, but that he consents that the extent of "as much as possible" varies with platform.

IMO part of this is also pointing out the license situation in the Coq chat to new users especially of VST (which I do from time to time).
