### ISSUE TITLE
Problem installing Coq on Mac OS 12.6.2

### ISSUE THREAD

**Issue by marcbezem** [coq/platform#325]
#### Description of the problem

I get: “Coq Platform 8.16 2022.09.app” can’t be opened because Apple cannot check it for malicious software.

And I'm asked to take contact with "the developer".

So this is what I do, any help is highly appreciated.

#### Coq Version

See above, but that doesn't seem to be the problem.

Marc Bezem

**Comment by Zimmi48** [comment]
@marcbezem answered to me:

>No, I hadn't seen that advice before now. Following the advice, I opened from the finder with Control-click (= Right-click) and got again a little window with a slightly different message, but now also an "Open" button, which I Control-clicked (just to be sure). Then Coqide opened. This was not the end of my adventures: Coqide cannot be closed with its own "Quit ..." command (nor with Command-Q), so I had to close it with Force Quit (I can live with that). Goodie: now Coqide also opens with only clicking (without Control), so one only has to Control-click once. That makes sense, as validating once is sufficient (I expect that every update should also be validated once). Thanks for your help. I hope my feedback is useful. Marc

I was not aware of this issue with quitting CoqIDE. Has someone else running macOS experimented it?

**Comment by MSoegtropIMC** [comment]
Regarding Quitting: for me CMD+Q, File/Quit and the red button all work. I start it with double click from the Applications folder or with single click from Launchpad.

Does CoqIDE work otherwise? It is not unheard of that MacOS temporarily decided to block the communication with coqidetop. Then CoqIDE hangs. This happens rarely to me, but it happens. Usually this is from start then (so I can't do anything with it). I have the same effect with other client/server apps like Maxima und wxMaxima (also rarely).

@marcbezem : one more question: did you read the ReadMe or Installation.html files provided in the installer? Would it have helped to put this information there in a prominent place? (I plan anyway to do so, but still I am curious).

**Comment by marcbezem** [comment]
No, on https://github.com/coq/platform/releases/tag/2022.09.1 I found under "Recommended binary installers" what I was looking for, and sparked the installation. From the point of view of webpage design, you could perhaps start with the next para "General information" and add "Read this first (in case your installation encounters a problem)". With "Recommended ..." first the reader is inclined to follow the recommendation :-)

Re CoqIDE: it works, but none of CMD+Q, File/Quit and the red button (upper left corner of Apple window) works, only Force Quit (where CoqIDE is not mentioned as "not responding").

**Comment by marcbezem** [comment]
Could you reproduce it? NB my Mac has not ARM but i5!

**Comment by MSoegtropIMC** [comment]
No the quitting works fine for me on both Apple and Intel silicon Macs. This is quite strange.

**Comment by MSoegtropIMC** [comment]
This got closed because I added a not on the "right click open" to the Install.html file included in the DMG.

Should we create a separate issue for the quite issue?

**Comment by MSoegtropIMC** [comment]
Triage note: the signing and notarisation for MacOS is anyway worked. The quitting problem could not be reprodced by others -> closing.
