### ISSUE TITLE
Request: windows arm64 native executable?

### ISSUE THREAD

**Issue by oscarbg** [coq/platform#419]
Note don’t hardware yet to test..

**Comment by MSoegtropIMC** [comment]
We will not support this unless there is a justification. An example for a justification would be e.g. that a substantial number of students in a course say they don't have anything else than an ARM Windows machine. So far I have not heard of a single such case.

Note that besides the manual work, supporting a platform consumes substantial amounts of electricity in CI testing, so this is not environmentally friendly to do this just because one could do it.

If there is a justification please reopen with the justification.
