### ISSUE TITLE
macOS installation instructions should probably not try to explain Homebrew vs MacPorts

### ISSUE THREAD

**Issue by tchajed** [coq/platform#432]
The macOS readme has a very long explanation of choosing Homebrew vs MacPorts. It's also out of date - on Apple Silicon, Homebrew installs to /opt/homebrew and not /usr/local. My suggestion is to **simply mention both and delete the long explanation.**

My main rationale is that the page currently attempts to give security advice about this decision, which I don't think the Coq Platform maintainers are in a position to give but especially to maintain. I also believe it unfairly maligns Homebrew by linking to a "controversy" that is 5 years old, but my point stands independent of this (but please take that bias into account).

If you are going by popularity, Homebrew is much more popular than MacPorts. [This page](https://www.scivision.dev/homebrew-macports-fink/) links to the official download statistics both tools track. opam was installed 1,800 times in the last 30 days on Homebrew and 26 on MacPorts. (Neither of these is even officially recommended; opam instead wants you to `curl | sh` install it).

**Comment by MSoegtropIMC** [comment]
I don't think the evaluation is unfair. I say:

> It is a dangerous thing to make /usr/local/bin writable to the current user, but the alternative - running sudo make install for 100 software packages - is also not free of danger. 

so both methods have their issues and I clearly state them.

The reason this section is there is that quite a few people installing Coq have neither (yes this does happen) and I think it is better to give some information which helps people making a choice efficiently. Without such information one can spend hours deciding between the two.

Regarding the security concerns: As far as I know it is still so that the homebrew install folder is writeble to non root users and at first position in the PATH after installing homebrew. So there is no difference in this. I also state that what opam does is very similar.

But I will definitely change the section on installation issues in /usr/local and mention that this is intel Mac only.

**Comment by MSoegtropIMC** [comment]
P.S.: if you have a link to a page making a comparison useful to Coq Platform users (e.g. mentioning that MacPorts is problematic behind a proxy) and kept up to date, I would be happy to replace my write up with a link.

**Comment by MSoegtropIMC** [comment]
@tchajed : unless you can provide a link which explains the pros and cons of Homebrew and MacPorts, I will close this issue. I am also happy to include any improvements to my text. But just deleting it as you suggest is IMHO not a good option.

**Comment by tchajed** [comment]
I can't find any article I would consider decent, so I'll just close the issue.

I would recommend you talk about threat models if you're going to give any security related advice, but I'm out of energy to contribute to this.
